apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xkhs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-xkhs@sha256:40ea05e6fa9ff612fda92ca087d794cc33be6cfd59d90e4f67978bfdb368ae2a
        name: my-nodejs
        resources: {}
status: {}
